USE codeup_test_db;
INSERT INTO albums (artist,name,release_date,sales,genre)
VALUES ('Nine_Inch_Nails','Pretty_Hate_Machine','1992','43','Industrial_Metal'),
('ABBA','Gold:_Greatest_Hits','1992','29','Pop'),
('Bon_Jovi','Slippery_When_Wet','1986','28','_Hard_rock/Glam_metal'),
('Various_artists', 'Grease:_The_Original_Soundtrack_from_the_Motion_Picture', '1978', '28', 'Soundtrack'),
('Mariah_Carey','Music_Box','1993','28','_Pop/R&B/Rock_'),
('Linkin_Park','Hybrid_Theory','2000','27','_Nu_metal/_Alternative_metal_'),
('Norah_Jones','Come_Away_with_Me','2002','27','Jazz'),
('Eric_Clapton','Unplugged','1992','26','_Acoustic_rock/_Acoustic_blues_'),
('Madonna','True_Blue','1986','25','Pop'),
('Bob_Marley_&_The_Wailers','Legend:_The_Best_of_Bob_Marley_&_The_Wailers','1984','25','Reggae'),
('Carole_King','Tapestry','1971','25','Pop'),
('Phil_Collins','No_Jacket_Required','1985','25','_Pop/Rock_'),
('Queen','Greatest_Hits','1981','25','Rock'),
('Simon_&_Garfunkel','Bridge_over_Troubled_Water','1970','25','Folk_rock'),
('U2','The_Joshua_Tree','1987','25','Rock'),
('Britney_Spears','Baby_One_More_Time','1999','25','Pop'),
('Whitney_Houston','Whitney_Houston','1985','25','_Pop/_R&B_'),
('Backstreet_Boys','Backstreet\'s_Back_/_Backstreet_Boys','1997','24','Pop'),
('Backstreet_Boys','Millennium','1999','24','Pop'),
('Spice__Girls','Spice','1996','23','Pop'),
('Ace__of_Base','Happy_Nation/The_Sign','1993','23','Pop'),
('Oasis','(Whats_the_Story),_Morning_Glory?','1995','22','_Britpop/_Rock_'),
('Madonna','Like_a_Virgin','1984','21','_Pop/_Dance_'),
('Eminem','Encore','2004','21','_Rap/_Hip_Hop_'),
('Bon_Jovi','Cross_Road','1994','21','_Hard_rock/_Glam_metal_'),
('Adele','25','2015','20','_Soul/_Pop/_R&B_'),
('Boston','Boston','1976','20','Hard_rock'),
('Britney_Spears','Oops!..._I_Did_It_Again','2000','20','Pop'),
('Def_Leppard','Hysteria','1987','20','_Pop/_Hard_rock_'),
('George_Michael','Faith','1987','20','_Pop/_R&B/_Funk/_Soul_'),
('Green_Day','Dookie','1994','20','_Pop_punk/_Punk_rock/_Alternative_rock_'),
('Lionel_Richie','Can\'t_Slow_Down','1983','20','_Pop/_R&B/_Soul_'),
('Mariah_Carey','Daydream','1995','20','_Pop/R&B_'),
('Michael_Jackson','_HIStory:_Past/_Present_and_Future/_Book_I_','1995','20','_Pop/_Rock/_R&B_'),
('Michael_Jackson','Off_the_Wall','1979','20','_Soul/_Disco/_R&B_'),
('Prince_&_the_Revolution','Purple_Rain','1984','20','_Pop/Rock/_R&B/_Soundtrack_'),
('Shania_Twain','The_Woman_in_Me','1995','20','_Country/_Pop_'),
('Supertramp','Breakfast_in_America','1979','20','_Progressive_rock/_Art_rock_'),
('Tracy_Chapman','Tracy_Chapman','1988','20','Folk_rock'),
('Various_artists','Flashdance:_Original_Soundtrack_from_the_Motion_Picture','1983','20','Soundtrack'),
('Whitney_Houston','Whitney','1987','20','_Pop/_R&B_');